config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/signup', to: 'users#new'
  
  # ログイン機能
  get     '/login', to: 'sessions#new'
  post    '/login', to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'
  
  resources :bases

  resources :users do
      member do
        patch 'update_basic_info'
        get 'attendances/edit_attendance_change_request'
        patch 'attendances/update_attendance_change_request'
        get 'attendances/edit_attendance_change_notice'
        patch 'attendances/update_attendance_change_notice'        
        get 'attendances/edit_overwork_request'
        patch 'attendances/update_overwork_request'
        get 'attendances/edit_overwork_notice'
        patch 'attendances/update_overwork_notice'
        get 'attendances/index_attendance_log'
        get 'attendances/edit_one_month_request'
        patch 'attendances/update_one_month_request'
        get 'attendances/edit_one_month_notice'
        patch 'attendances/update_one_month_notice'
        get 'attendances/new'
      end
      collection do
        get 'go_work'
        post :import
        get 'edit_basic_info'
      end
      resources :attendances, only: :update
    end
  end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  attr_accessor :remember_token
  before_save { self.email = email.downcase }

  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :department, length: { in: 2..30 }, allow_blank: true
  validates :basic_time, presence: true
  validates :work_time, presence: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  # 渡された文字列のハッシュ値を返す。
  def User.digest(string)
    cost =
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end
  
  #ランダムなトークンを返す。
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  #永続セッションのため、ハッシュ化したトークンをデータベースに記憶する。
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  #トークンがダイジェストと一致すればtrueを返す。
  def authenticated?(remember_token)
    return false if remember.digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  # ユーザーのログイン情報を破棄する。
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def self.search(search)
    if search
      where(['name LIKE ?', "%#{search}%"])
    else
      all
    end
  end

  def self.import(file)
    imported_num = 0

    open(file.path, 'r:cp932:utf-8', undef: :replace) do |f|
      csv = CSV.new(f, :headers => :first_row)
      csv.each do |row|
        next if row.header_row?

        table = Hash[[row.headers, row.fields].transpose]
        
        user = find_by(:id => table["id"])
        if user.nil?
          user = new
        end

        user.attributes = table.to_hash.slice(
                    *table.to_hash.except(:id, :created_at, :updated_at).keys)

        if user.valid?
          user.save!
          imported_num += 1
        end
      end
    end
    
    imported_num
  end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only:[:show, :edit, :update, :destroy, :update_basic_info]
  before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy, :update_basic_info]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:index, :destroy, :edit_basic_info, :update_basic_info, :go_work]
  # before_action :admin_or_correct_user, only: :show
  before_action :set_one_month, only: :show
  
  def index
    @users = User.paginate(page: params[:page]).search(params[:search]).order(id: "ASC")
    @search_user = params[:search]
  end
  
  def show
    @worked_sum = @attendances.where.not(started_at: nil).count
    @attendance_overwork_lists = Attendance.where("(overwork_request_destination = ?) AND (overwork_request_status = ?)", @user.id, "申請中")
    if @attendance_overwork_lists.nil?
      @attendance_overwork_request_count = "0"
    else
      @attendance_overwork_request_count = @attendance_overwork_lists.count
    end
    @attendance_modification_lists = Attendance.where("(modification_request_destination = ?) AND (modification_request_status = ?)", @user.id, "申請中")
    if @attendance_modification_lists.nil?
      @attendance_modification_request_count = "0"
    else
      @attendance_modification_request_count = @attendance_modification_lists.count
    end
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = '新規作成に成功しました'
      redirect_to attendances_edit_one_month_request_user_path(current_user)
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to attendances_edit_one_month_request_user_path(current_user)
    else
      render :edit
    end
  end
  
  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end
  
  def edit_basic_info
  end
  
  def update_basic_info
    if @user.update_attributes(basic_info_params)
      flash[:success] = "#{@user.name}の基本情報を更新しました。"
    else
      flash[:danger] = "#{@user.name}の更新は失敗しました。<br>" + @user.errors.full_messages.join("<br>")
    end
    redirect_to users_url
  end

  def go_work
    @users = User.all.includes(:attendances)
  end

  def import
    if params[:csv_file].blank?
      redirect_to(users_url, alert: 'インポートするCSVファイルを選択してください')
    else
      num = User.import(params[:csv_file])
      redirect_to(users_url, notice: "#{num.to_s}件のユーザー情報を追加 / 更新しました")
    end
  end
  
  private
  
    def user_params
      params.require(:user).permit(:name, :email, :department, :password, :password_confirmation)
    end
    
    def basic_info_params
      params.require(:user).permit(
        :name, :email, :department, :employee_number, :uid, :basic_work_time,:designed_work_start_time,
        :designed_work_end_time, :password, :password_confirmation)
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
  
  # 勤怠基本情報を指定のフォーマットで返す。
  def format_basic_info(time)
    if time.nil?
      nil
    else
      format("%.2f", (((time.hour * 60) + time.min) / 60.0))
    end
  end

  # 秒数の値を、時間単位に変更する（分母は分と秒の乗算）
  def overwork_time(time)
    format("%.2f", (time / 3600))
  end
  
end

app/views/users/_form.html.erb
<%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true, method: :patch) do |f| %>
  <%= render 'shared/error_messages_2' %>
  
  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>
  
  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :department, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :department, class: "form-control" %> 

  <%= f.label :employee_number, class: "label-#{yield(:class_text)}" %>
  <%= f.number_field :employee_number, class: "form-control" %>

  <%= f.label :uid, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :uid, class: "form-control" %>
 
  <%= f.label :basic_work_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :basic_work_time, class: "form-control" %>

  <%= f.label :designed_work_start_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :designed_work_start_time, class: "form-control" %> 

  <%= f.label :designed_work_end_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :designed_work_end_time, class: "form-control" %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>
  
  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation,class: "form-control" %>
  
  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/_form_2.html.erb
<%= form_with(model: @user, url: user_path(@user), local: true, method: :patch) do |f| %>
  <%= render 'shared/error_messages', object: @user %>
  
  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>
  
  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :department, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :department, class: "form-control" %> 

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>
  
  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation,class: "form-control" %>
  
  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/_form_3.html.erb
<%= form_with(model: @user, url: users_path, local: true, method: :post) do |f| %>
  <%= render 'shared/error_messages', object: @user %>
  
  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>
  
  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :department, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :department, class: "form-control" %> 

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>
  
  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation,class: "form-control" %>
  
  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, 'Edit') %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '更新') %>
<h1>アカウント情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form_2' %>
  </div>
</div>

app/views/users/edit_basic_info.html.erb
<% provide(:title, 'basic-info') %>
<% provide(:class_text, 'basic-info') %>
<% provide(:button_text, '更新') %>

<h1>基本情報の修正</h1>

app/views/users/go_work.html.erb
<% provide(:title, 'go_work Users') %>

<h1>出勤中社員一覧</h1>

<div class="col-md-10 col-md-offset-1">
  <table class="table table-condensed table-hover" id="table-users">
    <thead>
      <tr>
        <th><%= User.human_attribute_name :employee_number %></th>
        <th><%= User.human_attribute_name :name %></th>
      </tr>
    </thead>
    
    <% @users.each do |user| %>
      <% user.attendances.each do |attendance| %>
        <% if attendance.worked_on == Date.current && 
              attendance.started_at != nil && 
              attendance.finished_at == nil %>
          <tr>
            <td><%= user.employee_number %></td>
            <td><%= user.name %></td>
          </tr>
        <% end %>
      <% end %>
    <% end %>
  </table>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>
<% provide(:class_text, 'All User') %>
<% provide(:button_text, '更新') %>

<h1>ユーザー一覧</h1>

<div class="row">
  <div class="col-md-offset-8">
    <%= form_tag(users_path, method: :get) do %>
      <%= label_tag :name, "ユーザー名検索", class:"label-search" %>
      <div class="input-group">
        <%= text_field_tag :search, "", placeholder: "キーワードを入力...", class:"form-control" %>
        <span class="input-group-btn">
          <%= submit_tag '検索', :name => nil, class: "btn btn-primary" %>
        </span>
      </div>
    <% end %>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-body">
    <%= form_tag(import_users_path, method: :post, multipart: true) do %>
      <div class="form-group">
        <%= file_field_tag :csv_file %>
      </div>
      <%= submit_tag "CSVインポート", :class => "btn btn-primary" %>
    <% end %>
  </div>
</div>

<%= will_paginate %>
<table class="table">
  <% @users.each do |user| %>
    <tr>
      <td>
        <div class="col-md-22" col-md-offset-1>
        <% if current_user.admin? && !current_user?(user) %>
        <% @user = user %>
        <%= user.name %>
        <br>| <%= link_to "削除", user, method: :delete,
              data: { confirm: "削除してよろしいですか？" },
              class: "btn btn-primary" %><br>
          <div class="panel-group">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h4 class="panel-title">
                  <button type="button" data-toggle="collapse" data-target="#collapse<%= user.id %>" class="btn btn-primary btn-lg">編集</button>
                </h4>
              </div>
              <div id="collapse<%= user.id %>" class="panel-collapse collapse">
                <div class="panel-body"><%= render 'users/form', locals:{ user: @user } %></div>
              </div>
            </div>
          </div>
          <% end %>
        </div>
      </td>
    </tr>
  <% end %>
</table>
<%= will_paginate %>


<div id="edit-basic-info" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '新規作成') %>
<h1>アカウント作成</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form_3'  %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1>show.html.erb</h1>