config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/signup', to: 'users#new'
  
  # ログイン機能
  get     '/login', to: 'sessions#new'
  post    '/login', to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'
  
  resources :bases

  resources :users do
      member do
        patch 'update_basic_info'
        get 'attendances/edit_attendance_change_request'
        patch 'attendances/update_attendance_change_request'
        get 'attendances/edit_attendance_change_notice'
        patch 'attendances/update_attendance_change_notice'        
        get 'attendances/edit_overwork_request'
        patch 'attendances/update_overwork_request'
        get 'attendances/edit_overwork_notice'
        patch 'attendances/update_overwork_notice'
        get 'attendances/index_attendance_log'
        get 'attendances/edit_one_month_request'
        patch 'attendances/update_one_month_request'
        get 'attendances/edit_one_month_notice'
        patch 'attendances/update_one_month_notice'
        get 'attendances/new'
      end
      collection do
        get 'go_work'
        post :import
        get 'edit_basic_info'
      end
      resources :attendances, only: :update
    end
  end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  
  validates :worked_on, presence: true
  validates :note, length: { maximum: 50 }
  validate :finished_at_is_invalid_without_a_started_at
  validate :started_at_is_invalid_without_a_finished_at, on: :validate_one_month
  validate :initial_finished_at_is_invalid_without_a_initial_started_at
  validate :initial_started_at_is_invalid_without_a_initial_finished_at
  validate :before_change_finished_at_is_invalid_without_a_before_change_started_at
  validate :before_change_started_at_is_invalid_without_a_before_change_finished_at
  validate :after_change_finished_at_is_invalid_without_a_after_change_started_at
  validate :after_change_started_at_is_invalid_without_a_after_change_finished_at
  validate :started_at_than_finished_at_fast_if_invalid
  validate :initial_started_at_than_initial_finished_at_fast_if_invalid
  validate :before_change_started_at_is_invalid_without_a_before_change_finished_at
  validate :after_change_started_at_than_after_change_finished_at_fast_if_invalid  
  #validate :invalid_without_a_after_change_time
  #validate :after_time_invalid_without_a_modification_request_destination
  #validate :next_day_and_note_invalid_without_a_modification_request_destination
  
  def finished_at_is_invalid_without_a_started_at
    errors.add(:started_at, "が必要です") if started_at.blank? && finished_at.present?
  end
  
  def started_at_is_invalid_without_a_finished_at
    errors.add(:finished_at, "が必要です") if finished_at.blank? && started_at.present?
  end

  # 変更する退社時間のみ入力されている場合、申請を無効とする（初回版）。
  def initial_finished_at_is_invalid_without_a_initial_started_at
    errors.add(:initial_started_at, "が必要です") if initial_started_at.blank? && initial_finished_at.present? 
  end

  # 変更する出社時間のみ入力されている場合、申請を無効とする（初回版）。
  def initial_started_at_is_invalid_without_a_initial_finished_at
    errors.add(:initial_finished_at, "が必要です") if initial_finished_at.blank? && initial_started_at.present?
  end

  # 変更する退社時間のみ入力されている場合、申請を無効とする（一回申請後）。
  def before_change_finished_at_is_invalid_without_a_before_change_started_at
    errors.add(:before_change_started_at, "が必要です") if before_change_started_at.blank? && before_change_finished_at.present? 
  end
  
  # 変更する出社時間のみ入力されている場合、申請を無効とする（一回申請後）。
  def before_change_started_at_is_invalid_without_a_before_change_finished_at
    errors.add(:before_change_finished_at, "が必要です") if before_change_finished_at.blank? && before_change_started_at.present?
  end

  # 変更する退社時間のみ入力されている場合、申請を無効とする（二回申請以降）。
  def after_change_finished_at_is_invalid_without_a_after_change_started_at
    errors.add(:after_change_started_at, "が必要です") if after_change_started_at.blank? && after_change_finished_at.present? 
  end
  
  # 変更する出社時間のみ入力されている場合、申請を無効とする（二回申請以降）。
  def after_change_started_at_is_invalid_without_a_after_change_finished_at
    errors.add(:after_change_finished_at, "が必要です") if after_change_finished_at.blank? && after_change_started_at.present?
  end  

  # 退社時間が出社時間より早い場合は登録を無効にする
  def started_at_than_finished_at_fast_if_invalid
    if started_at.present? && finished_at.present? && (modification_next_day == false)
      errors.add(:started_at, "より早い退勤時間は無効です") if started_at > finished_at
    end
  end

  # 変更する退社時間が、変更する出社時間より早い場合、申請を無効とする（初回申請）。
  def initial_started_at_than_initial_finished_at_fast_if_invalid
    if initial_started_at.present? && initial_finished_at.present? && (modification_next_day == false)
      errors.add(:initial_started_at, "より早い退勤時間は無効です") if initial_started_at > initial_finished_at
    end
  end

  # 変更する退社時間が、変更する出社時間より早い場合、申請を無効とする（一回目承認後）。
  def before_change_started_at_than_before_change_finished_at_fast_if_invalid
    if before_change_started_at.present? && before_change_finished_at.present? && (modification_next_day == false)
      errors.add(:before_change_started_at, "より早い退勤時間は無効です") if before_change_started_at > before_change_finished_at
    end
  end

  # 変更する退社時間が、変更する出社時間より早い場合、申請を無効とする（２回目承認以降）。
  def after_change_started_at_than_after_change_finished_at_fast_if_invalid
    if after_change_started_at.present? && after_change_finished_at.present? && (modification_next_day == false)
      errors.add(:after_change_started_at, "より早い退勤時間は無効です") if after_change_started_at > after_change_finished_at
    end
  end

  # 変更する出社時間・退社時間が未入力でかつ申請先が入力されている場合、申請を無効とする。
  # ※errorsに対しての引数は複数に対してできるか分からないため、after_change_started_atを対象とした。
  def invalid_without_a_after_change_time
    errors.add(:after_change_started_at, "が必要です") if after_change_finished_at.blank? && after_change_started_at.blank? && modification_request_destination.present?
  end

  # 変更する出社時間・退社時間が入力してあるにも関わらず、上長が選択されていない場合、申請を無効とする。
  def after_time_invalid_without_a_modification_request_destination
    if initial_started_at.present? || initial_finished_at.present?
      errors.add(:modification_request_destination, "が必要です") if modification_request_destination.blank?
    end
  end

  # 翌日チェックまたは備考が入力してあっても、上長が選択されていない場合、申請を無効とする。
  def next_day_and_note_invalid_without_a_modification_request_destination
    if modification_next_day.present? || note.present?
      errors.add(:modification_next_day, "が必要です") if modification_request_destination.blank?
    end
  end  

  def started_at_time
    if started_at.present?
      started_at.strftime("%H：%M")
    end
  end

  def finished_at_time
    if finished_at.present?
      finished_at.strftime("%H：%M")
    end
  end  
  
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_user, only: [:new, :edit_attendance_change_request, :update_attendance_change_request, :edit_attendance_change_request, :edit_attendance_change_notice, :update_attendance_change_notice, 
                                  :edit_overwork_request, :update_overwork_request, :edit_overwork_notice, :update_overwork_notice, :index_attendance_log, :edit_one_month_request, :update_one_month_request,
                                  :edit_one_month_notice, :update_one_month_notice]
  before_action :logged_in_user, only: [:update, :edit_attendance_change_request, :update_attendance_change_request]
  before_action :admin_or_correct_user, only: [:update, :edit_attendance_change_request, :update_attendance_change_request]
  before_action :set_one_month, only: [:edit_attendance_change_request, :edit_overwork_request, :edit_overwork_notice, :edit_one_month_request]
  before_action :non_admin_user, only: [:edit_one_month_request, :edit_attendance_change_request]
  
  UPDATE_ERROR_MSG = "勤怠登録に失敗しました。やり直してください。" 

  require 'csv'

  # csv出力用のアクションとして定義
  def new
    @first_day = params[:date].nil? ? Date.current.beginning_of_month : params[:date].to_date
    @last_day = @first_day.end_of_month
    one_month = [*@first_day..@last_day]
    @attendance = Attendance.new
    @attendances = Attendance.where(user_id: @user.id).where(worked_on: one_month).order(worked_on: "ASC")
    respond_to do |format|
      format.html
      format.csv do |csv|
        send_attendances_csv(@attendances)
      end
    end
  end
  
  def update
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:id])
    if @attendance.started_at.nil?
      if @attendance.update_attributes(started_at: Time.current.change(sec: 0))
        flash[:info] = "おはようございます！"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    elsif @attendance.finished_at.nil?
      if @attendance.update_attributes(finished_at: Time.current.change(sec: 0))
        flash[:info] = "お疲れ様でした。"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    end
    redirect_to attendances_edit_one_month_request_user_path(current_user)
  end

  def edit_one_month_request
    @worked_sum = @attendances.where.not(started_at: nil).count
    @attendance = Attendance.where(user_id: @user.id).find_by(worked_on: @first_day)
    @attendance_one_month_lists = Attendance.where("(one_month_request_destination = ?) AND (one_month_request_status = ?)", @user.id, "申請中")
    if @attendance_one_month_lists.nil?
      @attendance_one_month_request_count = "0"
    else
      @attendance_one_month_request_count = @attendance_one_month_lists.count
    end
    @attendance_overwork_lists = Attendance.where("(overwork_request_destination = ?) AND (overwork_request_status = ?)", @user.id, "申請中")
    if @attendance_overwork_lists.nil?
      @attendance_overwork_request_count = "0"
    else
      @attendance_overwork_request_count = @attendance_overwork_lists.count
    end
    @attendance_modification_lists = Attendance.where("(modification_request_destination = ?) AND (modification_request_status = ?)", @user.id, "申請中")
    if @attendance_modification_lists.nil?
      @attendance_modification_request_count = "0"
    else
      @attendance_modification_request_count = @attendance_modification_lists.count
    end
  end

  def update_one_month_request
    one_month_request_params.each do |id, item|
      attendance = Attendance.find(id)
      if item[:one_month_request_destination].present? 
        if attendance.update_attributes(item)
          flash[:success] = "１ヶ月分の勤怠情報を申請しました。"
        else
          flash[:danger] = "勤怠情報の申請に失敗しました。"
        end
      else
        flash[:danger] = "上長を選択してください。"
      end
      redirect_to attendances_edit_one_month_request_user_path(current_user, date: @first_day)
    end
  end

  def edit_one_month_notice
    @request_users = User.where(id: Attendance.where("(one_month_request_destination = ?) AND (one_month_request_status = ?)", @user.id, "申請中").select(:user_id))
    @attendance_lists = Attendance.where("(one_month_request_destination = ?) AND (one_month_request_status = ?)", @user.id, "申請中").order(worked_on: "ASC")
    @attendance = Attendance.new
  end

  def update_one_month_notice
    update_judgement = "false"
    one_month_notice_params.each do |id,item|
      attendance = Attendance.find(id)
      if item[:one_month_change] == "true"
        if item[:one_month_request_status] == "承認"
        elsif item[:one_month_request_status] == "否認"
        elsif item[:one_month_request_status] == "なし" 
        else
        end
        item[:one_month_change] = nil
        attendance.update_attributes(item)
        update_judgement = "true"
        flash[:success] = "上長確認しました。"
      else
      end
    end
    unless update_judgement == "true"
      flash[:danger] = "上長確認する場合、変更ボタンにチェックを入れてください。"
    end
    redirect_to attendances_edit_one_month_request_user_path(current_user)
  end

  def edit_attendance_change_request
  end

  def update_attendance_change_request
    ActiveRecord::Base.transaction do
      attendance_change_request_params.each do |id, item|
        attendance = Attendance.find(id) 
          if item[:modification_request_destination].present?
            if item[:initial_started_at].present? && item[:initial_finished_at].present? 
              if item[:modification_next_day] == "true"
                year = (item[:worked_on].to_date + 1).year 
                month = (item[:worked_on].to_date + 1).month
                day = (item[:worked_on].to_date + 1).day 
              else
                year = (item[:worked_on].to_date).year 
                month = (item[:worked_on].to_date).month
                day = (item[:worked_on].to_date).day
              end
              hour = (item[:initial_finished_at].to_time).hour
              min = (item[:initial_finished_at].to_time).min
              year1 = (item[:worked_on].to_date).year 
              month1 = (item[:worked_on].to_date).month
              day1 = (item[:worked_on].to_date).day
              hour1 = (item[:initial_started_at].to_time).hour
              min1 = (item[:initial_started_at].to_time).min
              item[:initial_finished_at] = Time.new(year, month, day, hour, min, 0,).to_time
              item[:initial_started_at] = Time.new(year1, month1, day1, hour1, min1, 0,).to_time
            elsif item[:before_change_started_at].present? && item[:before_change_finished_at].present?
              if item[:modification_next_day] == "true"
                year = (item[:worked_on].to_date + 1).year 
                month = (item[:worked_on].to_date + 1).month
                day = (item[:worked_on].to_date + 1).day 
              else
                year = (item[:worked_on].to_date).year 
                month = (item[:worked_on].to_date).month
                day = (item[:worked_on].to_date).day
              end
              hour = (item[:before_change_finished_at].to_time).hour
              min = (item[:before_change_finished_at].to_time).min
              year1 = (item[:worked_on].to_date).year 
              month1 = (item[:worked_on].to_date).month
              day1 = (item[:worked_on].to_date).day
              hour1 = (item[:before_change_started_at].to_time).hour
              min1 = (item[:before_change_started_at].to_time).min
              item[:before_change_finished_at] = Time.new(year, month, day, hour, min, 0,).to_time
              item[:before_change_started_at] = Time.new(year1, month1, day1, hour1, min1, 0,).to_time
            elsif item[:after_change_started_at].present? && item[:after_change_finished_at].present?
              if item[:modification_next_day] == "true"
                year = (item[:worked_on].to_date + 1).year 
                month = (item[:worked_on].to_date + 1).month
                day = (item[:worked_on].to_date + 1).day 
              else
                year = (item[:worked_on].to_date).year 
                month = (item[:worked_on].to_date).month
                day = (item[:worked_on].to_date).day
              end
              hour = (item[:after_change_finished_at].to_time).hour
              min = (item[:after_change_finished_at].to_time).min
              year1 = (item[:worked_on].to_date).year 
              month1 = (item[:worked_on].to_date).month
              day1 = (item[:worked_on].to_date).day
              hour1 = (item[:after_change_started_at].to_time).hour
              min1 = (item[:after_change_started_at].to_time).min
              item[:after_change_finished_at] = Time.new(year, month, day, hour, min, 0,).to_time
              item[:after_change_started_at] = Time.new(year1, month1, day1, hour1, min1, 0,).to_time            
            end
            attendance.update_attributes!(item)
          end
        if item[:modification_request_destination].blank? && item[:initial_started_at].present? && item[:initial_finished_at].present?
          flash[:warning] = "上長を選択してないため、申請できていない日付があります。"
        end
      end
    end
      flash[:success] = "勤怠変更を申請しました。"
      redirect_to attendances_edit_one_month_request_user_path(current_user)
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = "無効な入力データがあったため、申請をキャンセルしました。"
    redirect_to attendances_edit_one_month_request_user_path(current_user)
  end

  def edit_attendance_change_notice
    @request_users = User.where(id: Attendance.where(modification_request_destination: @user.id).where(modification_request_status: "申請中").select(:user_id))
    @attendance_lists = Attendance.where("(modification_request_destination = ?) AND (modification_request_status = ?)", @user.id, "申請中").order(worked_on: "ASC")
    @attendance = Attendance.new
  end

  def update_attendance_change_notice
    update_judgement = "false"
    attendance_change_notice_params.each do |id,item|
      attendance = Attendance.find(id)
      if item[:modification_change] == "true"

app/helpers/attendances_helper.rb
module AttendancesHelper
  
  def working_times(start, finish)
    format("%.2f", (((finish - start) / 60) / 60.0))
  end

  # 秒数の値を、時間単位に変更する（分母は分と秒の乗算）
  def overwork_time(time)
    format("%.2f", (time / 3600))
  end
  
end

app/views/attendances/edit_attendance_change_notice.js.erb
$("#edit-attendance-change-notice").html("<%= escape_javascript(render 'edit_attendance_change_notice') %>");
$("#edit-attendance-change-notice").modal("show");

app/views/attendances/edit_one_month_notice.js.erb
$("#edit-one-month-notice").html("<%= escape_javascript(render 'edit_one_month_notice') %>");
$("#edit-one-month-notice").modal("show");

app/views/attendances/edit_one_month_request.html.erb
<% provide(:title, @user.name) %>

<table class="table table-bordered table-condensed user-table"  id="table-attendances">
  <tr>
    <td>
      <% if current_user?(@user) %>
        <%= link_to "←", attendances_edit_one_month_request_user_path(date: @first_day.prev_month), class: "btn btn-primary" %>
        &emsp;<%= l(@first_day, format: :middle) %>　時間管理表&emsp;
        <%= link_to "→", attendances_edit_one_month_request_user_path(date: @first_day.next_month), class: "btn btn-primary" %>
      <% else %>
        &emsp;<%= l(@first_day, format: :middle) %>　時間管理表&emsp;
      <% end %>
    </td>
    <td>
      <div>指定勤務開始時間　<%= format_basic_info(@user.designed_work_start_time) %></div>
      <div>指定勤務終了時間　<%= format_basic_info(@user.designed_work_end_time) %></div>
    </td>
    <td>基本時間　<%= format_basic_info(@user.basic_work_time) %></td>
    <td>初日　<%= l(@first_day, format: :short) %></td>
  </tr>
  <tr>
    <td>所属：<%= @user.department.present? ? @user.department : "未所属" %></td>
    <td>氏名：<%= @user.name %></td>
    <td>出勤日数：<%= @worked_sum %>日</td>
    <td>締日　<%= l(@last_day, format: :short) %></td>
  </tr>
</table>
<% if current_user?(@user) %>
  <div>
    <div>
      <% if @user.superior? %>
        <% if @attendance_one_month_request_count == 0 %>
          【所属長承認申請のお知らせ】
        <% else %>
          <%= link_to "【所属長承認申請のお知らせ】", attendances_edit_one_month_notice_user_path(@user), remote: true, class:"request-area" %>
          <div class="request-area"><%= @attendance_one_month_request_count %>件のお知らせがあります</div>
        <% end %>
      <% end %>
    </div>
    <div>
      <% if @user.superior? %>
        <% if @attendance_modification_request_count == 0 %>
          【勤怠変更申請のお知らせ】
        <% else %>
          <%= link_to "【勤怠変更申請のお知らせ】", attendances_edit_attendance_change_notice_user_path(@user), remote: true, class:"request-area" %>
          <div class="request-area"><%= @attendance_modification_request_count %>件のお知らせがあります</div>
        <% end %>
      <% end %>
    </div>
    <div>
      <% if @user.superior? %>
        <% if @attendance_overwork_request_count == 0 %>
        【残業申請のお知らせ】
        <% else %>
          <%= link_to "【残業申請のお知らせ】", attendances_edit_overwork_notice_user_path(@user), remote: true, class:"request-area" %>
          <div class="request-area"><%= @attendance_overwork_request_count %>件のお知らせがあります</div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="button-area">
    <div>
      <%= link_to "勤怠を編集", attendances_edit_attendance_change_request_user_path(date: @first_day), class:"btn btn-primary" %>
      <%= link_to "CSVを出力", attendances_new_user_path(format: :csv, date: params[:date]), class:"btn btn-primary" %>
    </div>
    <div>
      <%= link_to "勤怠修正ログ(承認済み)", attendances_index_attendance_log_user_path(@user), class:"btn btn-primary" %>
    </div>
  </div>
<% end %>
<table class="table table-bordered table-condensed table-hover" id="table-attendances">
  <thead>
    <tr>
      <!--rowspan:縦結合、colspan:横結合-->
      <th rowspan="3">残業申請</th>
      <th rowspan="3">日付</th>
      <th rowspan="3">曜日</th>
      <th rowspan="1" colspan="8">【実績】</th>
      <th rowspan="1" colspan="5">所定外勤務</th>
    </tr>
    <tr>  
      <th rowspan="1" colspan="3">出社</th>
      <th rowspan="1" colspan="3">退社</th>
      <th rowspan="2">在社時間</th>
      <th rowspan="2">備考</th>
      <th rowspan="1" colspan="2">終了予定時間</th>
      <th rowspan="2">時間外時間</th>
      <th rowspan="2">業務処理内容</th>        
      <th rowspan="2">指示者確認㊞</th>   
    </tr>
    <tr>
      <th>時</th>
      <th>分</th>
      <th>　　　</th>
      <th>時</th>
      <th>分</th>
      <th>　　　</th>
      <th>時</th>
      <th>分</th>        
    </tr>
  </thead>
  <tbody>
      <% @attendances.each do |day| %>
        <% css_class = case day.worked_on.wday
                       when 6 then 'text-primary'
                       when 0 then 'text-danger'
                       end %>
        <tr>
          <td>
            <% if current_user?(@user) %>
              <%= link_to "残業申請", attendances_edit_overwork_request_user_path(@user, date: day.worked_on), remote: true, class: "btn btn-primary" %>
            <% end %>
          </td>
          <td><%= l(day.worked_on, format: :short) %></td>
          <td class = "<%= css_class %>"><%= $days_of_the_week[day.worked_on.wday] %></td>
          <td><%= day.started_at.floor_to(15.minutes).hour if day.started_at.present? %></td>
          <td><%= day.started_at.floor_to(15.minutes).min if day.started_at.present? %></td>
          <td>
            <% if current_user?(@user) %>
              <% if (Date.current == day.worked_on) && day.started_at.nil? %>
                <%= link_to "出社", user_attendance_path(@user, day), method: :patch, class:"btn btn-primary btn-attendance" %>
              <% end %>
            <% end %>
          </td>
          <td><%= day.finished_at.floor_to(15.minutes).hour if day.finished_at.present? %></td>
          <td><%= day.finished_at.floor_to(15.minutes).min if day.finished_at.present? %></td>
          <td>
            <% if current_user?(@user) %>
              <% if (Date.current == day.worked_on) && day.started_at.present? && day.finished_at.nil? %>
                <%= link_to "退社", user_attendance_path(@user, day), method: :patch, class:"btn btn-primary btn-attendance" %>
              <% end %> 
            <% end %>             
          </td>
          <td>
            <% if day.started_at.present? && day.finished_at.present? %>
              <%= str_times = working_times(day.started_at.floor_to(15.minutes), day.finished_at.floor_to(15.minutes)) %>
              <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
            <% end %>
          </td>
          <td><%= day.note %></td>
          <td><%= l(day.scheduled_finished_at.floor_to(15.minutes), format: :hour) if day.scheduled_finished_at? %></td>
          <td><%= l(day.scheduled_finished_at.floor_to(15.minutes), format: :min) if day.scheduled_finished_at? %></td>
          <td><%= day.over_work_time if day.over_work_time? %></td>
          <td><%= day.business_processing_content %></td>
          <td>
            <div>
              <% if day.overwork_request_destination.present? && day.overwork_request_status == "申請中" %>
                <%= User.find_by(id: day.overwork_request_destination).name %>に残業申請中。
              <% elsif day.overwork_request_destination.present? && day.overwork_request_status == "承認" %>
                残業申請が<%= day.overwork_request_status %>されました。
              <% elsif day.overwork_request_destination.present? && day.overwork_request_status == "否認" %>
                残業申請が<%= day.overwork_request_status %>されました。              
              <% elsif day.overwork_request_status == "なし" %>
                残業申請が取り消されました。
              <% end %>
            </div>
            <div>
              <% if day.modification_request_destination.present? && day.modification_request_status == "申請中" %>
                <%= User.find_by(id: day.modification_request_destination).name %>に勤怠変更申請中。
              <% elsif day.modification_request_destination.present? && day.modification_request_status == "承認" %>
                勤怠変更申請が<%= day.modification_request_status %>されました。
              <% elsif day.modification_request_destination.present? && day.modification_request_status == "否認" %>
                勤怠変更申請が<%= day.modification_request_status %>されました。              
              <% elsif day.modification_request_status == "なし" %>
                勤怠変更申請が取り消されました。
              <% end %>
            </div>
          </td>                                            
        </tr>
      <% end %>  
    </tbody>
    <tfoot>
      <tr>
        <td colspan="3">累計日数</td>
        <td colspan="8">総合勤務時間</td>
        <td colspan="5">累計在社時間</td>
      </tr>
      <tr>
        <td colspan="3"><%= @attendances.count %>日</td>
        <td colspan="8"><%= format_basic_info(@user.work_time).to_f * @worked_sum %>時間</td>
        <td colspan="5"><%= format("%.2f", @total_working_times.to_f) %>時間</td>         
      </tr>       
      <tr>
        <!--空白行-->
        <td rowspan="2" colspan="15"></td>
        <!--所属長申請のステータスの表示-->
        <td rowspan="1" colspan="1">
          <% if @attendance.one_month_request_status.nil? %>
            <div>所属長承認　未</div>
          <% elsif @attendance.one_month_request_status == "申請中" %>
            <div><%= User.find_by(id: @attendance.one_month_request_destination).name %>に勤怠申請中</div>
          <% elsif @attendance.one_month_request_status == "なし" %>
            <div><%= User.find_by(id: @attendance.one_month_request_destination).name %>に取り消されました</div>
          <% else %>
            <div><%= User.find_by(id: @attendance.one_month_request_destination).name %>に<%= @attendance.one_month_request_status %>されました</div>
          <% end %>
          <% if current_user?(@user) %>
            <%= form_with(model: @user, url: attendances_update_one_month_request_user_path(@user), local: true, method: :patch) do |f| %>
              <%= f.fields_for "attendances[]", @attendance do |attendance| %>
                <div><%= attendance.collection_select :one_month_request_destination, User.all.where(superior: true).where.not(id: current_user.id).order(:id), :id, :name, {include_blank: "上長を選択してください", selected: nil}, {class: "form-control"} %></div>
                <div class="btn-one-month"><%= f.submit "申請", class: "btn btn-lg btn-primary" %></div>
                <%= attendance.hidden_field :one_month_request_status, value: "申請中" %>
              <% end %>
            <% end %>
          <% end %>
        </td>
      </tr>
    </tfoot>
  </table>

  <div id="edit-one-month-notice" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
  <div id="edit-overwork-request" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
  <div id="edit-overwork-notice" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
  <div id="edit-attendance-change-notice" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/attendances/edit_overwork_notice.js.erb
$("#edit-overwork-notice").html("<%= escape_javascript(render 'edit_overwork_notice') %>");
$("#edit-overwork-notice").modal("show");

app/views/attendances/edit_overwork_request.js.erb
$("#edit-overwork-request").html("<%= escape_javascript(render 'edit_overwork_request') %>");
$("#edit-overwork-request").modal("show");