config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/signup', to: 'users#new'
  
  # ログイン機能
  get     '/login', to: 'sessions#new'
  post    '/login', to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'
  
  resources :bases

  resources :users do
      member do
        patch 'update_basic_info'
        get 'attendances/edit_attendance_change_request'
        patch 'attendances/update_attendance_change_request'
        get 'attendances/edit_attendance_change_notice'
        patch 'attendances/update_attendance_change_notice'        
        get 'attendances/edit_overwork_request'
        patch 'attendances/update_overwork_request'
        get 'attendances/edit_overwork_notice'
        patch 'attendances/update_overwork_notice'
        get 'attendances/index_attendance_log'
        get 'attendances/edit_one_month_request'
        patch 'attendances/update_one_month_request'
        get 'attendances/edit_one_month_notice'
        patch 'attendances/update_one_month_notice'
        get 'attendances/new'
      end
      collection do
        get 'go_work'
        post :import
        get 'edit_basic_info'
      end
      resources :attendances, only: :update
    end
  end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse", id="header">
  <div class="container">
  <% if logged_in? %>
    <% unless current_user.admin? %>
      <%= link_to "勤怠システム", attendances_edit_one_month_request_user_path(current_user), id: "logo" %>
    <% else %>
      <%= link_to "勤怠システム", root_path, id: "logo" %>
    <% end %>
  <% end %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <% unless current_user.admin? %>
            <li><%= link_to "トップへ", attendances_edit_one_month_request_user_path(current_user) %></li>
          <% else %>
            <li><%= link_to "トップへ", root_path %></li>
          <% end %>
          <% if current_user.admin? %> 
            <li><%= link_to "ユーザー一覧", users_path %></li>
            <li><%= link_to "出勤社員一覧", go_work_users_path %></li>
            <li><%= link_to "拠点情報の修正", bases_path %></li>
            <li><%= link_to "基本情報の修正", edit_basic_info_users_path %></li>
          <% end %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= current_user.name %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <% unless current_user.admin? %>
                  <li><%= link_to "勤怠システム", attendances_edit_one_month_request_user_path(current_user) %></li>
                  <li><%= link_to "設定", edit_user_path(current_user) %></li>
                <% end %>
                <li class="divider"></li>
                <li>
                  <%= link_to "ログアウト", logout_path, method: :delete %> 
                </li>
              </ul>
            </li>
        <% else %>
          <li><%= link_to "トップへ", root_path %></li>        
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, msg| %>
        <div class="alert alert-<%= message_type %>"><%= msg.html_safe %></div>
      <% end %>
    <%= yield %>
    </div>
  </body>
</html>